INSERT INTO db_fotoalbum.posts (title, description, url, is_visible, created_at, updated_at) VALUES ('Lorem Ipsum', 'Descrizione del mio primo post', 'https://picsum.photos/id/15/800/800', 1, '2023-03-30 11:33:50', '2023-03-30 11:33:50');
INSERT INTO db_fotoalbum.posts (title, description, url, is_visible, created_at, updated_at) VALUES ('Nuovo Post', 'Descrizione del mio secondo post', 'https://picsum.photos/id/18/800/800', 1, '2023-03-30 11:33:50', '2023-03-30 11:33:50');
INSERT INTO db_fotoalbum.posts (title, description, url, is_visible, created_at, updated_at) VALUES ('Sic Amet', 'Descrizione del mio terzo post', 'https://picsum.photos/id/13/800/800', 1, '2023-03-30 11:33:50', '2023-03-30 11:33:50');
INSERT INTO db_fotoalbum.posts (title, description, url, is_visible, created_at, updated_at) VALUES ('Altra Foto', 'Descrizione del mio quarto post', 'https://picsum.photos/id/14/800/800', 0, '2023-03-30 11:33:50', '2023-03-30 11:33:50');
INSERT INTO db_fotoalbum.posts (title, description, url, is_visible, created_at, updated_at) VALUES ('Lorem Ipsum 2', 'Descrizione del mio quinto post', 'https://picsum.photos/id/19/800/800', 1, '2023-03-30 11:33:50', '2023-03-30 11:33:50');
INSERT INTO db_fotoalbum.posts (title, description, url, is_visible, created_at, updated_at) VALUES ('New Cover', 'Descrizione del mio sesto post', 'https://picsum.photos/id/22/800/800', 0, '2023-03-30 11:33:50', '2023-03-30 11:33:50');
INSERT INTO db_fotoalbum.posts (title, description, url, is_visible, created_at, updated_at) VALUES ('Collection 3', 'Descrizione del mio settimo post', 'https://picsum.photos/id/29/800/800', 1, '2023-03-30 11:33:50', '2023-03-30 11:33:50');
INSERT INTO db_fotoalbum.categories (name) VALUES ('portrait');
INSERT INTO db_fotoalbum.categories (name) VALUES ('landscape');
INSERT INTO db_fotoalbum.categories (name) VALUES ('macro');
INSERT INTO db_fotoalbum.categories (name) VALUES ('sports');
INSERT INTO db_fotoalbum.categories (name) VALUES ('event');
INSERT INTO db_fotoalbum.categories (name) VALUES ('long exposure');
INSERT INTO db_fotoalbum.categories (name) VALUES ('black and white');
INSERT INTO db_fotoalbum.categories (name) VALUES ('retro');
INSERT INTO db_fotoalbum.categories (name) VALUES ('nature');
INSERT INTO db_fotoalbum.categories (name) VALUES ('art');
INSERT INTO db_fotoalbum.categories (name) VALUES ('graffiti');
INSERT INTO db_fotoalbum.categories (name) VALUES ('gallery');
INSERT INTO db_fotoalbum.users (email, first_name, last_name, password) VALUES('cri@email.com', 'Cristina', 'Lietti', '{noop}cri');
INSERT INTO db_fotoalbum.users (email, first_name, last_name, password) VALUES('anna@email.com', 'Anna', 'Wulfson', '{noop}anna');
INSERT INTO db_fotoalbum.roles (id, name) VALUES (1, 'ADMIN');
INSERT INTO db_fotoalbum.roles (id, name) VALUES (2, 'USER');
INSERT INTO db_fotoalbum.users_roles (user_id, roles_id) VALUES (1, 1);
INSERT INTO db_fotoalbum.users_roles (user_id, roles_id) VALUES (2, 2);
INSERT INTO db_fotoalbum.category_post (post_id, category_id) VALUES (1, 2);
INSERT INTO db_fotoalbum.category_post (post_id, category_id) VALUES (1, 5);
INSERT INTO db_fotoalbum.category_post (post_id, category_id) VALUES (1, 11);
INSERT INTO db_fotoalbum.category_post (post_id, category_id) VALUES (2, 1);
INSERT INTO db_fotoalbum.category_post (post_id, category_id) VALUES (2, 8);
INSERT INTO db_fotoalbum.category_post (post_id, category_id) VALUES (2, 10);
INSERT INTO db_fotoalbum.category_post (post_id, category_id) VALUES (3, 3);
INSERT INTO db_fotoalbum.category_post (post_id, category_id) VALUES (3, 4);
INSERT INTO db_fotoalbum.category_post (post_id, category_id) VALUES (4, 6);
INSERT INTO db_fotoalbum.category_post (post_id, category_id) VALUES (4, 5);
INSERT INTO db_fotoalbum.category_post (post_id, category_id) VALUES (5, 9);
INSERT INTO db_fotoalbum.category_post (post_id, category_id) VALUES (6, 12);
INSERT INTO db_fotoalbum.category_post (post_id, category_id) VALUES (6, 7);
INSERT INTO db_fotoalbum.category_post (post_id, category_id) VALUES (7, 8);
INSERT INTO db_fotoalbum.category_post (post_id, category_id) VALUES (7, 2);
INSERT INTO db_fotoalbum.category_post (post_id, category_id) VALUES (7, 11);
INSERT INTO db_fotoalbum.category_post (post_id, category_id) VALUES (7, 12);